""" add columns for entry fee

Revision ID: 9c4469b7261b
Revises: c25c4cedcad7
Create Date: 2018-04-30 13:55:54.242503

"""

# revision identifiers, used by Alembic.
revision = '9c4469b7261b'
down_revision = 'c25c4cedcad7'

from alembic import op
import sqlalchemy as sa
from SqliteDecimal import SqliteDecimal

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entry_fee', SqliteDecimal(length=12, collation=2), nullable=True))
        batch_op.add_column(sa.Column('entry_fee_paid_amount', SqliteDecimal(length=12, collation=2), nullable=True))
        batch_op.add_column(sa.Column('entry_fee_paid_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('entry_fee_paid_date')
        batch_op.drop_column('entry_fee_paid_amount')
        batch_op.drop_column('entry_fee')

    # ### end Alembic commands ###
