"""empty message

Revision ID: c25c4cedcad7
Revises: 15ba537337c4
Create Date: 2018-04-27 18:00:37.448566

"""

# revision identifiers, used by Alembic.
revision = 'c25c4cedcad7'
down_revision = '15ba537337c4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.Unicode(length=20), nullable=True))
        batch_op.add_column(sa.Column('payment_sdd_bic', sa.Unicode(length=34), nullable=True))
        batch_op.add_column(sa.Column('payment_sdd_iban', sa.Unicode(length=34), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('payment_sdd_iban')
        batch_op.drop_column('payment_sdd_bic')
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
