"""member type+fee cols

Revision ID: cbcea62674f1
Revises: 2fbe1bde5df8
Create Date: 2018-04-23 22:57:58.020018

"""

# revision identifiers, used by Alembic.
revision = 'cbcea62674f1'
down_revision = '2fbe1bde5df8'

from alembic import op
import sqlalchemy as sa
from SqliteDecimal import SqliteDecimal


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fee', SqliteDecimal(length=12, collation=2), nullable=True))
        batch_op.add_column(sa.Column('member_type', sa.Unicode(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('member_type')
        batch_op.drop_column('fee')

    # ### end Alembic commands ###
