"""create bcgv18, drop old ones

Revision ID: e1f47a02b79b
Revises: cbcea62674f1
Create Date: 2018-04-23 13:52:27.440873

"""

# revision identifiers, used by Alembic.
revision = 'e1f47a02b79b'
down_revision = 'cbcea62674f1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_invite_date_bcgv18', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('email_invite_flag_bcgv18', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_invite_token_bcgv18', sa.Unicode(length=255), nullable=True))
        batch_op.drop_column('email_invite_token_bcgv15')
        batch_op.drop_column('email_invite_token_bcgv17')
        batch_op.drop_column('email_invite_token_bcgv16')
        batch_op.drop_column('email_invite_date_bcgv17')
        batch_op.drop_column('email_invite_date_bcgv16')
        batch_op.drop_column('email_invite_date_bcgv15')
        batch_op.drop_column('email_invite_date_bcgv14')
        batch_op.drop_column('email_invite_flag_bcgv15')
        batch_op.drop_column('email_invite_flag_bcgv14')
        batch_op.drop_column('email_invite_flag_bcgv17')
        batch_op.drop_column('email_invite_flag_bcgv16')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_invite_flag_bcgv16', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('email_invite_flag_bcgv17', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('email_invite_flag_bcgv14', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('email_invite_flag_bcgv15', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('email_invite_date_bcgv14', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('email_invite_date_bcgv15', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('email_invite_date_bcgv16', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('email_invite_date_bcgv17', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('email_invite_token_bcgv16', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('email_invite_token_bcgv17', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('email_invite_token_bcgv15', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('email_invite_token_bcgv18')
        batch_op.drop_column('email_invite_flag_bcgv18')
        batch_op.drop_column('email_invite_date_bcgv18')

    # ### end Alembic commands ###
