"""add sdd_bankname column

Revision ID: e20effdbe44c
Revises: 9c4469b7261b
Create Date: 2018-04-30 16:41:59.208426

"""

# revision identifiers, used by Alembic.
revision = 'e20effdbe44c'
down_revision = '9c4469b7261b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_sdd_bankname', sa.Unicode(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('payment_sdd_bankname')

    # ### end Alembic commands ###
